### ISSUE TITLE
This is more of a list of suggestions

### ISSUE THREAD

**Issue by Chaosyr** [RageLeague/InscryptionMoreSliderPuzzles#1]
1. Change the received packs a player gets when finishing a slider to One for balance reasons.

2. Randomize Order of Slider Puzzles instead of being in the order `.pdef` files are loaded have them be within a random order.

3. Probably not super feasible but the ability to make these for act 1 or act 3 would be ubers fun to mess around with.

4. Maybe add a Configurable reward via a 5th line or something.

**Comment by RageLeague** [comment]
Hi.
This mod is mainly for me to play around with modding in Unity. As such, I don't have any plans to update the mod. Sorry :(
